{
	"bowlGames": ["Hitler Bowl", "Lincoln Bowl", "Churchill Bowl", " Victoria Bowl", "Washington Bowl", "Napoleon Bowl", "Genghis Bowl", "Stalin Bowl", "Aristotle Bowl", " Prophet Bowl"],
	"conferences": [{
		"confName": "NAM",
		"confFullName": "North American",
		"confTeams": [{
			"name": "Canada",
			"abbreviation": "CAN",
			"prestige": "80",
			"state": "Maine",
			"rival": "USA"
		}, {
			"name": "Costa Rica",
			"abbreviation": "CRC",
			"prestige": "50",
			"state": "Florida",
			"rival": "HON"
		}, {
			"name": "Cuba",
			"abbreviation": "CUB",
			"prestige": "70",
			"state": "Florida",
			"rival": "JAM"
		}, {
			"name": "Dominican Republic",
			"abbreviation": "DOM",
			"prestige": "40",
			"state": "Alabama",
			"rival": "HAI"
		}, {
			"name": "Guatemala",
			"abbreviation": "GUA",
			"prestige": "40",
			"state": "Texas",
			"rival": "MEX"
		}, {
			"name": "Haiti",
			"abbreviation": "HAI",
			"prestige": "35",
			"state": "Louisiana",
			"rival": "DOM"
		}, {
			"name": "Honduras",
			"abbreviation": "HON",
			"prestige": "60",
			"state": "Arkansas",
			"rival": "MEX"
		}, {
			"name": "Jamaica",
			"abbreviation": "JAM",
			"prestige": "65",
			"state": "Mississippi",
			"rival": "CUB"
		}, {
			"name": "Mexico",
			"abbreviation": "Mex",
			"prestige": "75",
			"state": "Florida",
			"rival": "Hon"
		}, {
			"name": "United States of America",
			"abbreviation": "USA",
			"prestige": "95",
			"state": "Kentucky",
			"rival": "CAN"
		}]
	}, {
		"confName": "SAM",
		"confFullName": "South America",
		"confTeams": [{
			"name": "Argentina",
			"abbreviation": "ARG",
			"prestige": "90",
			"state": "Ohio",
			"rival": "BRA"
		}, {
			"name": "Bolivia",
			"abbreviation": "BOL",
			"prestige": "35",
			"state": "Michigan",
			"rival": "ECU"
		}, {
			"name": "Brazil",
			"abbreviation": "BRA",
			"prestige": "90",
			"state": "Michigan",
			"rival": "ARG"
		}, {
			"name": "Chile",
			"abbreviation": "CHI",
			"prestige": "80",
			"state": "Wisconsin",
			"rival": "PER"
		}, {
			"name": "Columbia",
			"abbreviation": "COL",
			"prestige": "70",
			"state": "Minnesota",
			"rival": "VEN"
		}, {
			"name": "Ecuador",
			"abbreviation": "ECU",
			"prestige": "50",
			"state": "Illinois",
			"rival": "BOL"
		}, {
			"name": "Paraguay",
			"abbreviation": "PAR",
			"prestige": "75",
			"state": "Iowa",
			"rival": "URU"
		}, {
			"name": "Peru",
			"abbreviation": "PER",
			"prestige": "55",
			"state": "Indiana",
			"rival": "CHI"
		}, {
			"name": "Uruguay",
			"abbreviation": "URU",
			"prestige": "80",
			"state": "Pennsylvania",
			"rival": "PAR"
		}, {
			"name": "Venezuela",
			"abbreviation": "VEN",
			"prestige": "85",
			"state": "Nebraska",
			"rival": "COL"
		}]
	}, {
		"confName": "EUR",
		"confFullName": "Europe",
		"confTeams": [{
			"name": "France",
			"abbreviation": "FRA",
			"prestige": "65",
			"state": "New York",
			"rival": "GER"
		}, {
			"name": "Germany",
			"abbreviation": "GER",
			"prestige": "80",
			"state": "Virginia",
			"rival": "FRA"
		}, {
			"name": "Ireland",
			"abbreviation": "IRL",
			"prestige": "75",
			"state": "Maryland",
			"rival": "ENG"
		}, {
			"name": "Italy",
			"abbreviation": "ITA",
			"prestige": "60",
			"state": "Virginia",
			"rival": "ESP"
		}, {
			"name": "Netherlands",
			"abbreviation": "NED",
			"prestige": "60",
			"state": "Maryland",
			"rival": "SWE"
		}, {
			"name": "Russia",
			"abbreviation": "RUS",
			"prestige": "85",
			"state": "New Jersey",
			"rival": "TUR"
		}, {
			"name": "Spain",
			"abbreviation": "ESP",
			"prestige": "65",
			"state": "Massachusetts",
			"rival": "ITA"
		}, {
			"name": "Sweden",
			"abbreviation": "SWE",
			"prestige": "60",
			"state": "Pennsylvania",
			"rival": "NED"
		}, {
			"name": "Turkey",
			"abbreviation": "TUR",
			"prestige": "60",
			"state": "RUS",
			"rival": "PIT"
		}, {
			"name": "England",
			"abbreviation": "ENG",
			"prestige": "85",
			"state": "Indiana",
			"rival": "IRE"
		}]
	}, {
		"confName": "ASIA",
		"confFullName": "Asia",
		"confTeams": [{
			"name": "China PR",
			"abbreviation": "CHN",
			"prestige": "90",
			"state": "Oklahoma",
			"rival": "JPN"
		}, {
			"name": "India",
			"abbreviation": "IND",
			"prestige": "80",
			"state": "Texas",
			"rival": "PAK"
		}, {
			"name": "Iran",
			"abbreviation": "IRN",
			"prestige": "75",
			"state": "Texas",
			"rival": "IRQ"
		}, {
			"name": "Iraq",
			"abbreviation": "IRQ",
			"prestige": "80",
			"state": "Texas",
			"rival": "IRN"
		}, {
			"name": "Israel",
			"abbreviation": "ISR",
			"prestige": "65",
			"state": "KSA",
			"rival": "TCU"
		}, {
			"name": "Japan",
			"abbreviation": "JPN",
			"prestige": "75",
			"state": "Hawaii",
			"rival": "CHN"
		}, {
			"name": "North Korea",
			"abbreviation": "PRK",
			"prestige": "75",
			"state": "Kansas",
			"rival": "KOR"
		}, {
			"name": "Pakistan",
			"abbreviation": "PAK",
			"prestige": "70",
			"state": "West Virginia",
			"rival": "IND"
		}, {
			"name": "Saudi Arabia",
			"abbreviation": "KSA",
			"prestige": "50",
			"state": "Kansas",
			"rival": "ISR"
		}, {
			"name": "South Korea",
			"abbreviation": "KOR",
			"prestige": "65",
			"state": "Ohio",
			"rival": "PRK"
		}]
	}, {
		"confName": "AFR",
		"confFullName": "Africa",
		"confTeams": [{
			"name": "Cameroon",
			"abbreviation": "CMR",
			"prestige": "65",
			"state": "California",
			"rival": "GHA"
		}, {
			"name": "Ivory Coast",
			"abbreviation": "CIV",
			"prestige": "80",
			"state": "Oregon",
			"rival": "NGA"
		}, {
			"name": "Egypt",
			"abbreviation": "EGY",
			"prestige": "75",
			"state": "California",
			"rival": "KEN"
		}, {
			"name": "Nigera",
			"abbreviation": "NGA",
			"prestige": "65",
			"state": "California",
			"rival": "CIV"
		}, {
			"name": "Rwanda",
			"abbreviation": "RWA",
			"prestige": "35",
			"state": "Oregon",
			"rival": "UGA"
		}, {
			"name": "South Africa",
			"abbreviation": "RSA",
			"prestige": "60",
			"state": "Hawaii",
			"rival": "TAN"
		}, {
			"name": "Tanzania",
			"abbreviation": "TAN",
			"prestige": "50",
			"state": "California",
			"rival": "RSA"
		}, {
			"name": "Uganda",
			"abbreviation": "UGA",
			"prestige": "50",
			"state": "Oregon",
			"rival": "RWA"
		}, {
			"name": "Ghana",
			"abbreviation": "GHA",
			"prestige": "60",
			"state": "California",
			"rival": "CMR"
		}, {
			"name": "Kenya",
			"abbreviation": "KEN",
			"prestige": "60",
			"state": "Idaho",
			"rival": "EGY"
		}]
	}, {
		"confName": "ROW",
		"confFullName": "Rest of World",
		"confTeams": [{
			"name": "Australia",
			"abbreviation": "AUS",
			"prestige": "80",
			"state": "Colorado",
			"rival": "NZL"
		}, {
			"name": "New Zealand",
			"abbreviation": "NZL",
			"prestige": "55",
			"state": "New Mexico",
			"rival": "AUS"
		}, {
			"name": "Papua New Guinea",
			"abbreviation": "PNG",
			"prestige": "45",
			"state": "Utah",
			"rival": "SAM"
		}, {
			"name": "Samoa",
			"abbreviation": "SAM",
			"prestige": "45",
			"state": "Colorado",
			"rival": "PNG"
		}, {
			"name": "Monaco",
			"abbreviation": "MON",
			"prestige": "50",
			"state": "New Mexico",
			"rival": "MAC"
		}, {
			"name": "Macau",
			"abbreviation": "MAC",
			"prestige": "70",
			"state": "Utah",
			"rival": "MON"
		}, {
			"name": "Singapore",
			"abbreviation": "SIN",
			"prestige": "60",
			"state": "Wyoming",
			"rival": "HKG"
		}, {
			"name": "Hong Kong",
			"abbreviation": "HKG",
			"prestige": "55",
			"state": "SIN",
			"rival": "WYO"
		}, {
			"name": "Thailand",
			"abbreviation": "THA",
			"prestige": "70",
			"state": "Arizona",
			"rival": "IDN"
		}, {
			"name": "Indonesia",
			"abbreviation": "IDN",
			"prestige": "65",
			"state": "Arizona",
			"rival": "THA"
		}]
	}]
}
